require("options")
require("keymaps")
require("plugins")
require("autocmd")
require("colorscheme_config")

-- plugins specific settings
require("_completion")
require("lsp")
require("treesitter")
require("statusbar")
require("_gitsigns")
require("formatter_config")
require("nvim-tree_config")
require("toggleTerm_config")
